language: java
env:
  global:
    - MAVEN_OPTS="-Xmx2g"
    # include $HOME for aws command
    - PATH=$HOME/.local/bin:$PATH
    # provide secret keys, so that awscli understands them
    - travis encrypt AWS_ACCESS_KEY_ID=$S3_KEY_ID --add
    - travis encrypt AWS_SECRET_ACCESS_KEY=$S3_KEY --add

script: mvn -Prelease -Dmaven.test.redirectTestOutputToFile -Dmatsim.preferLocalDtds=true

# install awscli command line tool to sync files to s3
before_deploy: pip install --user awscli

deploy:
  provider: script
  skip_cleanup: true
  script:
    # upload the release to aws s3
    - aws s3 cp ./target/nemo-0.0.1-SNAPSHOT-release.zip s3://mercartor-nemo-build-files/nemo-recent-build.zip
  on:
     branch: master
