language: java
jdk: oraclejdk8
addons:
  ssh_known_hosts: cluster.math.tu-berlin.de
  apt:
    packages:
      - oracle-java8-installer  # https://github.com/travis-ci/travis-ci/issues/3259
env:
  global:
    - MAVEN_OPTS="-Xmx2g"

script: mvn -Prelease -Dmaven.test.redirectTestOutputToFile -Dmatsim.preferLocalDtds=true

deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy.sh $SSH_KEY $MATH_CLUSTER_USER
  on:
     branch: master
