language: java
jdk: oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer  # https://github.com/travis-ci/travis-ci/issues/3259
env:
  global:
    - MAVEN_OPTS="-Xmx2g"

script: mvn test -B -Dmaven.test.redirectTestOutputToFile -Dmatsim.preferLocalDtds=true

deploy:
  provider: script
  script: bash deploy.sh $MATH_CLUSTER_USER $MATH_CLUSTER_PASSWORD
  on:
     branch: master
